apps:
  pages:
  - number: 1
    items:
    - Safari
    - Boxy for Gmail
    - Boxy for Calendar
    - Notes
    - Reminders
    - OmniFocus
    - Wunderlist
    - Alfred 3
    - Moom
    - CloudPull
    - KeepingYouAwake
    - TogglDesktop
    - NordVPN IKE
    - SelfControl
    - 1Password 7
    - Cloudup
    - Spotify
    - Photos
    - iA Writer
    - Sublime Text
    - Dropbox
    - App Store
    - Google Chrome
    - Maps
    - Atom
    - iTerm
    - System Preferences
    - folder: Social Networking
      pages:
      - number: 1
        items:
        - Messages
        - Skype
        - WhatsApp
        - FaceTime
        - Slack
        - Android Messages
        - Caprine
    - folder: Office
      pages:
      - number: 1
        items:
        - Pages
        - Numbers
        - Keynote
        - OmniGraffle
        - Preview
        - Contacts
        - Account Tracker
        - Calendar
        - Calculator
        - GhosteryLite
        - TweetDeck
        - Boxy Dashboard
    - folder: Entertainment
      pages:
      - number: 1
        items:
        - iBooks
        - GarageBand
        - iTunes
        - Photo Booth
    - folder: Developer Tools
      pages:
      - number: 1
        items:
        - Xcode
        - Apache CouchDB
        - Cyberduck
        - SiteSucker
        - Sourcetree
        - Activity Monitor
        - Anaconda-Navigator
        - Keybase
        - Terminal
        - DB Browser for SQLite
    - folder: Utilities
      pages:
      - number: 1
        items:
        - The Unarchiver
        - AppCleaner
        - DaisyDisk
        - Cloud Printer
        - CloudPrintSimpleProxy
        - AnyDesk
        - Monity
        - Siri
        - dupeGuru
    - folder: Graphics & AV
      pages:
      - number: 1
        items:
        - Sketch
        - ImageOptim
        - Classic Color Meter
        - Photos Duplicate Cleaner
        - MPlayerX
        - Gifski
        - Pixelmator
        - VLC
        - HandBrake
    - folder: TeX
      pages:
      - number: 1
        items:
        - Mendeley Desktop
        - Zotero
    - folder: System
      pages:
      - number: 1
        items:
        - TextEdit
        - Grapher
        - Time Machine
        - Font Book
        - Stickies
        - Image Capture
        - VoiceOver Utility
        - AirPort Utility
        - Migration Assistant
        - Console
        - Keychain Access
        - System Information
        - Automator
        - Script Editor
        - Disk Utility
        - Boot Camp Assistant
        - Digital Color Meter
        - ColorSync Utility
        - Grab
        - Bluetooth File Exchange
        - Audio MIDI Setup
        - XQuartz
        - Dictionary
        - Mission Control
        - Dashboard
        - Mail
        - DVD Player
        - QuickTime Player
        - Chess
widgets:
  pages:
  - number: 1
    items:
    - Unit Converter
    - Stocks
    - Stickies
    - Dictionary
    - Web Clip
    - Calculator
    - Movies
    - Tile Game
    - Weather
    - Contacts
    - World Clock
  - number: 2
    items:
    - Calendar
dock_items:
- Safari
- Boxy for Gmail
- Boxy for Calendar
- Notes
- Photos
- Messages
- Caprine
- App Store
- Spotify
- iTerm
- System Preferences
- ============
- Downloads
desktop: {}
